[package]
name = "twitter-text-parse-go"
version = "0.1.0"
authors = ["myl7 <myl@myl.moe>"]
license = "MIT"
edition = "2018"

[dependencies]
libc = "0.2"
twitter-text = "0.2"
twitter_text_config = "0.2"

[lib]
crate-type = ["staticlib"]
