name: CI
on:
  push:
    branches:
      - main
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [ x86_64-unknown-linux-gnu, x86_64-unknown-linux-musl ]
    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: ${{ matrix.target }}
          default: true
      - run: cargo build --release --target ${{ matrix.target }}
        working-directory: twitter-text-parse-go
      - uses: actions/upload-artifact@v2
        with:
          name: libtwitter_text_parse_go-${{ matrix.target }}.a
          path: twitter-text-parse-go/target/${{ matrix.target }}/release/libtwitter_text_parse_go.a
