name: CI
on:
  push:
    branches:
      - main
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true
      - name: Build
        run: bash build/build.sh
      - uses: actions/upload-artifact@v2
        with:
          name: libtwitter_text_parse_go
          path: lib
