name: CI
on:
  push:
    branches:
      - dev
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true
      - name: Build
        run: bash build/build.sh
      - name: Test gnu
        run: go run test/gnu_main/main.go
      - uses: actions/upload-artifact@v2
        with:
          name: lib
          path: lib
